#!/usr/bin/env python3
"""Generate `docs/DATA_DICTIONARY.md` from the live warehouse.

Generated rather than hand-written so it cannot drift from the schema: the
descriptions come from each model's own `-- description:` header, and the
columns and row counts come from the database itself.

    python scripts/build_data_dictionary.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
from sqlalchemy import inspect, text

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.config import SQL_DIR, get_warehouse  # noqa: E402
from src.etl.sql_runner import parse_model  # noqa: E402

OUT = ROOT / "docs" / "DATA_DICTIONARY.md"

LAYERS = [
    ("Staging", "stg_", "Raw CSVs, typed and de-duplicated. No business logic. "
                        "Hidden from the LLM agent."),
    ("Dimensions", "dim_", "Conformed descriptive entities shared by every fact."),
    ("Facts", "fact_", "Measured events, each at a single declared grain."),
    ("Marts", "mart_", "Pre-aggregated analytics, one per business question. "
                       "These are what the dashboard and the agent read."),
]

GRAINS = {
    "fact_orders": "one row per `order_id`",
    "fact_order_items": "one row per `order_id` + `order_item_id`",
    "fact_payments": "one row per `order_id` + `payment_sequential`",
    "dim_customer": "one row per person (`customer_unique_id`)",
    "dim_product": "one row per `product_id`",
    "dim_seller": "one row per `seller_id`",
    "dim_date": "one row per calendar day",
    "dim_geography": "one row per postcode prefix",
    "mart_rfm": "one row per customer",
    "mart_kpi_daily": "one row per day",
    "mart_kpi_monthly": "one row per month",
    "mart_cohort_retention": "one row per cohort × months-since-first-order",
    "mart_order_funnel": "one row per month × funnel stage",
    "mart_category_performance": "one row per product category",
    "mart_geo_performance": "one row per state",
    "mart_delivery_performance": "one row per month × region × delivery-speed bucket",
    "mart_payment_mix": "one row per month × instrument × instalment band",
    "mart_customer_360": "one row per customer (view over dim_customer + mart_rfm)",
}


def main() -> int:
    wh = get_warehouse()
    insp = inspect(wh.engine)
    tables = set(insp.get_table_names()) | set(insp.get_view_names())
    if not tables:
        print("Warehouse is empty — run `python -m src.etl.run_pipeline` first.")
        return 1

    descriptions = {}
    for path in sorted((SQL_DIR / "models").glob("*.sql")):
        model = parse_model(path)
        descriptions[model.name] = (model.description, model.materialized, path.name)

    lines: list[str] = [
        "# Data dictionary",
        "",
        "Generated by `python scripts/build_data_dictionary.py` — do not edit by hand.",
        "Descriptions come from each model's own header in `sql/models/`; columns and",
        "row counts come from the built warehouse.",
        "",
        f"Backend at generation time: **{wh.dialect}**.",
        "",
        "---",
        "",
    ]

    with wh.engine.connect() as conn:
        for layer, prefix, blurb in LAYERS:
            members = sorted(t for t in tables if t.startswith(prefix))
            if not members:
                continue
            lines += [f"## {layer}", "", blurb, ""]

            for table in members:
                rows = conn.execute(text(f"SELECT COUNT(*) FROM {table}")).scalar_one()
                desc, mat, src = descriptions.get(table, ("", "table", ""))
                lines.append(f"### `{table}`")
                lines.append("")
                meta = [f"**{rows:,} rows**"]
                if grain := GRAINS.get(table):
                    meta.append(f"grain: {grain}")
                if src:
                    meta.append(f"source: [`sql/models/{src}`](../sql/models/{src})")
                    meta.append(f"materialised as {mat}")
                lines.append(" · ".join(meta))
                lines.append("")
                if desc:
                    lines += [f"> {desc}", ""]

                sample = pd.read_sql(f"SELECT * FROM {table} LIMIT 200", wh.engine)
                lines += ["| Column | Type | Example |", "|---|---|---|"]
                for col in insp.get_columns(table):
                    name = col["name"]
                    dtype = str(col["type"]).split("(")[0].lower()
                    if dtype in {"null", "none", ""} and name in sample:
                        dtype = str(sample[name].dtype)
                    example = ""
                    if name in sample and not sample[name].dropna().empty:
                        example = str(sample[name].dropna().iloc[0])[:34]
                        example = example.replace("|", "\\|")
                    lines.append(f"| `{name}` | {dtype} | {example} |")
                lines.append("")

            lines.append("---")
            lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(lines):,} lines, "
          f"{len([t for t in tables])} tables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
